nodeSelector:
  kubernetes.io/os: linux

settings:
      aws:
        defaultInstanceProfile: ${node_iam_instance_profile}
        clusterName: ${eks_cluster_id}
        clusterEndpoint: ${eks_cluster_endpoint}
      featureGates:
          driftEnabled: true

controller:
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 400Mi

podAnnotations:
  co.elastic.logs/enabled: "true"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "Addons-Services"
          operator: In
          values:
          - "true"
