global:
  defaultResources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 20m
      memory: 200Mi

  proxy:
    resources:
      requests:
        cpu: 10m
        memory: 80Mi
      limits:
        cpu: 20m
        memory: 160Mi

pilot:
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 100Mi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "Addons-Services"
            operator: In
            values:
            - "true"
