affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "Addons-Services"
          operator: In
          values:
          - "true"

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 20m
    memory: 256Mi
