corednsdeploymentname: "coredns"
minReplicas: 2
maxReplicas: 10
targetCPUUtilizationPercentage: 80
targetMemoryUtilizationPercentage: 80

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "Addons-Services"
          operator: In
          values:
          - "true"

resources:
  limits:
    cpu: 300m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi
